AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application that uses the ASP.NET Core framework running in Amazon Lambda.
Parameters: {}
Conditions: {}
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service: lambda.amazonaws.com

  CloudWatchLogsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CloudwatchPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*'
      Roles:
        - !Ref LambdaRole
  
  TestIamApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM
        InvokeRole: NONE

  AspNetCoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: IamApi::IamApi.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnet6
      CodeUri: ""
      MemorySize: 1042
      Timeout: 30
      Role: !GetAtt LambdaRole.Arn
      Policies:
      - AWSLambda_FullAccess
      Events:
        ProxyResource:
          Type: Api
          Properties:
            RestApiId: !Ref TestIamApi
            Path: /{proxy+}
            Method: ANY
        RootResource:
          Type: Api
          Properties:
            RestApiId: !Ref TestIamApi
            Path: /
            Method: ANY

  IamApiSigV4LogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AspNetCoreFunction}"
      RetentionInDays: 30
  
  ApiTestUser:
    Type: AWS::IAM::User
    Properties:
      Path: /
      UserName: !Sub "${AWS::StackName}-user"

  ApiTestPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-policy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - execute-api:Invoke
          Resource: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${TestIamApi}/Prod/*/*"
          Effect: Allow
      Users:
        - !Ref ApiTestUser

  ApiTestUserCredentials:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref ApiTestUser

  ApiTestUserCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: !Sub "${AWS::StackName}-credentials-secret"
      SecretString: !Sub '{"ACCESS_KEY":"${ApiTestUserCredentials}", "SECRET_KEY":"${ApiTestUserCredentials.SecretAccessKey}"}'


Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value:
      !Sub https://${TestIamApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  TestUserSecretArn:
    Description: the Arn of the secrets manager secret where the test user Access Key and Secret Key are stored.
    Value: !Ref ApiTestUserCredentialsSecret

